"""
Django settings for Trading project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path 
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# M-Pesa API configuration
MPESA_ENVIRONMENT = 'sandbox'
MPESA_CONSUMER_KEY = 'your_consumer_key'
MPESA_CONSUMER_SECRET = 'your_consumer_secret'
MPESA_SHORTCODE = 'your_shortcode'
MPESA_PASS_KEY = 'your_pass_key'
MPESA_CALLBACK_URL = 'https://your-domain.com/mpesa/callback/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fdablk=z5695eff=+awo*3-hr5l*m6e^y7f&-hwk&agh*iet*='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_daraja',
    'base.apps.BaseConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Trading.urls'

AUTH_USER_MODEL = 'base.CustomUser'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            (BASE_DIR/ 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Trading.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGIN_URL = 'login'
STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# M-PESA CONFIGURATION (Django Daraja)
# ============================================
# 
# SANDBOX SETUP (For Testing):
# - Use these values for development and testing
# - No real money is involved
# - Test phone: 254708374149
#
# PRODUCTION SETUP (When You Get PayBill):
# 1. Change MPESA_ENVIRONMENT to 'production'
# 2. Replace MPESA_CONSUMER_KEY with your production key
# 3. Replace MPESA_CONSUMER_SECRET with your production secret
# 4. Replace MPESA_SHORTCODE with YOUR PayBill number
# 5. Replace MPESA_PASSKEY with your production passkey
# 6. Update MPESA_CALLBACK_URL with your live domain
#
# Get Production Credentials:
# - Visit https://developer.safaricom.co.ke/
# - Create production app
# - Copy Consumer Key & Secret
# - Get PassKey from Safaricom Business Team
# ============================================

# Current Environment (Change to 'production' when going live)
MPESA_ENVIRONMENT = 'sandbox'

# Sandbox Credentials (Replace when you get PayBill)
MPESA_CONSUMER_KEY = 'your_consumer_key_here'  # TODO: Replace with actual key
MPESA_CONSUMER_SECRET = 'your_consumer_secret_here'  # TODO: Replace with actual secret
MPESA_SHORTCODE = '174379'  # Sandbox test shortcode | TODO: Replace with YOUR PayBill number
MPESA_EXPRESS_SHORTCODE = '174379'  # Same as shortcode
MPESA_SHORTCODE_TYPE = 'paybill'  # Keep as 'paybill'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'  # Sandbox passkey | TODO: Replace
MPESA_INITIATOR_USERNAME = 'testapi'  # TODO: Replace with your initiator name
MPESA_INITIATOR_SECURITY_CREDENTIAL = 'your_security_credential'  # TODO: Replace

# Callback URL (IMPORTANT: Update when deploying)
# For local testing, use ngrok: https://ngrok.com/
# Example: MPESA_CALLBACK_URL = 'https://abc123.ngrok.io/mpesa/callback/'
MPESA_CALLBACK_URL = 'https://yourdomain.com/mpesa/callback/'  # TODO: Update with your domain

# Transaction timeout (in seconds)
MPESA_TIMEOUT_URL = 'https://yourdomain.com/mpesa/timeout/'  # TODO: Update with your domain

