# Generated by Django 5.2.6 on 2025-09-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='images',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.thumbnail'),
        ),
    ]
