# Generated by Django 5.2.6 on 2025-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price in Kenyan Shillings (KSh). Leave at 0 for free tutorials.', max_digits=10, null=True),
        ),
    ]
