# Generated by Django 5.2.6 on 2025-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tutorial_currencypair_subscription_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
