# Generated by Django 5.2.6 on 2025-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tutorial_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafiles',
            name='images',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='MediaFiles',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
