# Generated by Django 5.2.6 on 2025-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_mediafiles_images_tutorial_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
