# Generated by Django 5.2.1 on 2025-06-13 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False, help_text='Mark as complete')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, help_text='Set the due date', null=True)),
                ('categories', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
