# Generated by Django 5.2.1 on 2025-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.CharField(blank=True, choices=[('more important', 'more important'), ('important', 'important'), ('less important', 'less important')], max_length=20),
        ),
    ]
